#!/bin/sh

export DISPLAY=:0
SNAPSHOT=/tmp/snip-$(date +%Y-%m-%d-%H-%M-%S).jpg
MODES="$@"
ORIGINAL_SLEEP_TIME=`gsettings get org.gnome.desktop.session idle-delay | awk '{print $2}'`
SLEEP_TIME=$(($ORIGINAL_SLEEP_TIME+60))
SLEEP_TIME_MS=$(($SLEEP_TIME*1000))

is() {
    echo $MODES | grep --quiet -w "$1"
    return $?
}

isNot() {
    if is $1 ; then
        return 1
    fi
    return 0
}

log() {
    if isNot debug ; then
        echo "[$(date --rfc-email)] $1" >> /tmp/faux.log
    else
        echo "[$(date --rfc-email)] $1"
    fi
}

log "=================================="
log "faux-lock started"
log "SLEEP_TIME=$SLEEP_TIME"

if isNot debug ; then
    # Give us some time to escape
    sleep 5
else
    log "DEBUG=true"
fi

if is bait ; then
    log "BAIT=true"
    # Disabling screen lock
    gsettings set org.gnome.desktop.session idle-delay 0
fi

log "Lock trap is now armed"

# Reset lockscreen
gsettings set org.gnome.desktop.screensaver picture-uri ''

# Detect movement
IDLE=0
NEW_IDLE=0
while sleep 0.2 ; do
    NEW_IDLE=`xprintidle`
    if [ $NEW_IDLE -lt $IDLE ] ; then
        log "Someone caught!"
        break
    elif isNot bait && [ $NEW_IDLE -gt $SLEEP_TIME_MS ] ; then
        log "Lockscreen kicking in, shutting down faux-lock"
        exit
    fi
    IDLE=$NEW_IDLE
done

# SNIP!
ffmpeg -f video4linux2 -s 640x480 -i /dev/video0 -frames 1 $SNAPSHOT

# Fancy-up snapshot
convert $SNAPSHOT -resize 140% -gravity center -background black -pointsize 32 -set caption 'Caught in the act... SHAME!' -polaroid 5 $SNAPSHOT

log "Intruder captured at $SNAPSHOT"

if isNot debug ; then
    # Set lockscreen of shame
    gsettings set org.gnome.desktop.screensaver picture-uri "file://$SNAPSHOT"

    # Lock screen
    gnome-screensaver-command --lock
fi

if is bait ;
    # Restore original screen lock
    gsettings set org.gnome.desktop.session idle-delay $ORIGINAL_SLEEP_TIME
fi
